[customizations.installer.kickstart]
contents = """

# Unnatended install
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --utc
text --non-interactive
rootpw --lock
reboot

# leave free space on the "redhat" VG for the LVM Storate operator
zerombr
clearpart --all --initlabel
part /boot/efi --fstype=efi --size=200
part /boot --fstype=xfs --asprimary --size=800
part pv.01 --grow
volgroup rhel pv.01
logvol / --vgname=rhel --fstype=xfs --size=10240 --name=root

network --bootproto=dhcp --device=link --activate --onboot=on

%post --log=/var/log/anaconda/post-install.log --erroronfail

# Local user for console login and SSH
useradd -g wheel core
echo "core:redhat123" | chpasswd
mkdir /home/core/.ssh
cat > /home/core/.ssh/authorized_keys << EOFSSH
REPLACE_WTH_SSH_PUB_KEY
EOFSSH

# Need a pull secret to download container images from whatever registries we need (if umages are not embedded into the bootc image)
cat > /etc/crio/openshift-pull-secret <<EOFPULLS
REPLACE_WTH_PULL_SECRET
EOFPULLS
chmod 600 /etc/crio/openshift-pull-secret

# Set a hostname, just for convenience
echo "ushift" > /etc/hostname
chmod 644 /etc/hostname

%end
"""

