# The mirror config only includes MicroShift images
FROM servera.lab.example.com:8443/rhel9/rhel-bootc:9.5

COPY yum.d/* /etc/yum.repos.d/

RUN dnf install -y firewalld microshift microshift-release-info && \
    systemctl enable microshift && \
    dnf clean all

# Mandatory firewall configuration for OVNK + exposing SSH and Kubernetes API ports
RUN firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16 && \
    firewall-offline-cmd --zone=trusted --add-source=169.254.169.1 && \
    firewall-offline-cmd --zone=public --add-port=22/tcp && \
    firewall-offline-cmd --zone=public --add-port=6443/tcp

# Create a systemd unit to recursively make the root filesystem subtree
# shared as required by OVN images
RUN cat > /etc/systemd/system/microshift-make-rshared.service <<'EOF'
[Unit]
Description=Make root filesystem shared
Before=microshift.service
ConditionVirtualization=container
[Service]
Type=oneshot
ExecStart=/usr/bin/mount --make-rshared /
[Install]
WantedBy=multi-user.target
EOF
RUN systemctl enable microshift-make-rshared.service

# Use the mirror registry for MicroShift containers
ADD 999-microshift-mirror.conf /etc/containers/registries.conf.d/999-microshift-mirror.conf
ADD containers-policy.json.nosigs /etc/containers/policy.json
ADD quay-rootCA.pem /etc/pki/ca-trust/source/anchors
RUN update-ca-trust

# First-boot unit to copy the kubeconfig for the core user home dir

RUN cat > /etc/microshift/firstboot-microshift-user <<EOF
set -euxo pipefail

if [ -d /var/home/core ]; then
  while ! [ -r /var/lib/microshift/resources/kubeadmin/kubeconfig ]; do
    sleep 1
  done
  sudo cp /var/lib/microshift/resources/kubeadmin/kubeconfig /var/home/core/local-admin
  sudo cp /var/lib/microshift/resources/kubeadmin/ushift/kubeconfig /var/home/core/remote-admin
  sudo chown core /var/home/core/{local,remote}-admin
  chmod a-w /var/home/core/{local,remote}-admin
  echo 'export KUBECONFIG=~/local-admin' >> /var/home/core/.bashrc
  ls -la /var/home/core/ > /root/home-core
fi
EOF

RUN cat > /etc/systemd/system/firstboot-microshift-user.service <<EOF
[Unit]
Type=oneshot
Requires=microshift.service
After=microshift.service

[Service]
ExecStart=bash /etc/microshift/firstboot-microshift-user

[Install]
WantedBy=default.target
EOF

RUN systemctl enable firstboot-microshift-user

# From https://developers.redhat.com/articles/2025/02/26/best-practices-building-bootable-containers?source=sso#best_practices_for_linting
RUN bootc container lint
