FROM servera.lab.example.com:8443/rhel9/rhel-bootc:9.5
#FROM registry.redhat.io/rhel9/rhel-bootc:9.5

# Is there a way of adding all files from a directory at once?
ADD rhel-9.5-for-x86_64-baseos-rpms.repo /etc/yum.repos.d/rhel-9.5-for-x86_64-baseos-rpms.repo
ADD rhel-9.5-for-x86_64-appstream-rpms.repo /etc/yum.repos.d/rhel-9.5-for-x86_64-appstream-rpms.repo
ADD rhocp-4.17-for-rhel-9-x86_64-rpms.repo /etc/yum.repos.d/rhocp-4.17-for-rhel-9-x86_64-rpms.repo
ADD fast-datapath-for-rhel-9-x86_64-rpms.repo /etc/yum.repos.d/fast-datapath-for-rhel-9-x86_64-rpms.repo

RUN dnf install -y firewalld microshift && \
    systemctl enable microshift && \
    dnf clean all

# Mandatory firewall configuration
RUN firewall-offline-cmd --zone=public --add-port=22/tcp && \
    firewall-offline-cmd --zone=public --add-port=6443/tcp && \
    firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16 && \
    firewall-offline-cmd --zone=trusted --add-source=169.254.169.1

# Create a systemd unit to recursively make the root filesystem subtree
# shared as required by OVN images
RUN cat > /etc/systemd/system/microshift-make-rshared.service <<'EOF'
[Unit]
Description=Make root filesystem shared
Before=microshift.service
ConditionVirtualization=container
[Service]
Type=oneshot
ExecStart=/usr/bin/mount --make-rshared /
[Install]
WantedBy=multi-user.target
EOF
RUN systemctl enable microshift-make-rshared.service

# Use the mirror registry for MicroShift containers
ADD mirror-pull-secret /etc/crio/openshift-pull-secret
ADD 999-microshift-mirror.conf /etc/containers/registries.conf.d/999-microshift-mirror.conf
ADD containers-policy.json.nosigs /etc/containers/policy.json
ADD quay-rootCA.pem /etc/pki/ca-trust/source/anchors
RUN update-ca-trust

# Just to make it easier to SSH into the machine, while testing as a libvirt VM
RUN echo 'ushift' > /etc/hostname

# First-boot unit to copy the kubeconfig, like I did for OSTREE

# Remove user and create it using kickstart

RUN useradd -m -d /var/home/redhat -G wheel redhat && \
    echo "redhat:redhat123" | chpasswd

