name = "rhel9-microshift"
description = "Base blueprint with microshift"
version = "0.1.0"
modules = []
groups = []
distro = ""

[customizations]
hostname = "ushift"

[[packages]]
name = "microshift"

[customizations.services]
enabled = ["sshd", "microshift", "firstboot-microshift"]

[customizations.firewall.services]
enabled = ["ssh"]

[customizations.firewall]
ports = ["6443:tcp"]

[[customizations.files]]
path = "/etc/crio/openshift-pull-secret"
mode = "0600"
user = "root"
group = "root"
data = """
{
      "auths": {
              "servera.lab.example.com:8443": {
                      "auth": "bWljcm9zaGlmdDpyZWRoYXQxMjM="
              }
      }
}
"""

[[customizations.files]]
path = "/etc/pki/ca-trust/source/anchors/quay-rootCA.pem"
mode = "0644"
user = "root"
group = "root"
data = """
REPLACE_QUAY_CA
"""

[[customizations.files]]
path = "/etc/containers/registries.conf.d/999-microshift-mirror.conf"
mode = "0644"
user = "root"
group = "root"
data = """
[[registry]]
    prefix = ""
    location = "servera.lab.example.com:8443"
    mirror-by-digest-only = true
    insecure = false

[[registry]]
    prefix = ""
    location = "quay.io"
    mirror-by-digest-only = true
[[registry.mirror]]
    location = "servera.lab.example.com:8443"
    insecure = false

[[registry]]
    prefix = ""
    location = "registry.redhat.io"
    mirror-by-digest-only = true
[[registry.mirror]]
    location = "servera.lab.example.com:8443"
    insecure = false

[[registry]]
    prefix = ""
    location = "registry.access.redhat.com"
    mirror-by-digest-only = true
[[registry.mirror]]
    location = "servera.lab.example.com:8443"
    insecure = false
"""

[[customizations.files]]
path = "/etc/containers/policy.json"
mode = "0644"
user = "root"
group = "root"
data = """
{
	"default": [
    	{
        	"type": "insecureAcceptAnything"
    	}
	],
	"transports":
    	{
        	"docker-daemon":
            	{
                	"": [{"type":"insecureAcceptAnything"}]
            	}
    	}
}
"""
# Firstboot script to configure firewall for pod/service networks and mirror registry CA
[[customizations.files]]
path = "/etc/systemd/system/firstboot-microshift.service"
data = """
[Service]
Type=oneshot
ExecStart=update-ca-trust
ExecStart=firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16
ExecStart=firewall-offline-cmd --zone=trusted --add-source=169.254.169.1

[Install]
WantedBy=default.target
"""

