name = "rhel9-edge"
description = "blueprint-rhel9-edge"
version = "0.1.0"
modules = []
groups = []
distro = ""

[[packages]]
name = "httpd"

[customizations]
hostname = "edge"

[customizations.services]
enabled = ["sshd", "httpd"]

[customizations.firewall.services]
enabled = ["ssh", "http"]
